### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by thapelomokwane** [renatahodovan/fuzzinator#6]
Good day,

I'm trying to test fuzzinator but I get this error after pip installing it and trying to run it:

`Traceback (most recent call last):
  File "/usr/local/bin/fuzzinator", line 11, in <module>
    load_entry_point('fuzzinator==16.10', 'console_scripts', 'fuzzinator')()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/fuzzinator/__init__.py", line 8, in <module>
    from .controller import Controller
  File "/usr/local/lib/python2.7/dist-packages/fuzzinator/controller.py", line 21, in <module>
    from .mongo_driver import MongoDriver
  File "/usr/local/lib/python2.7/dist-packages/fuzzinator/mongo_driver.py", line 77
    exec=0)
       ^
SyntaxError: invalid syntax
`

I have put 'alias python='python3.5' in my .bashrc so that the requirements of python 3.5 are fullfiled for fuzzinator. Could you assist?

**Comment by renatahodovan** [comment]
@thapelomokwane: according to the log it seems that fuzzinator is still loaded by the python2.7 interpreter. The reason is probably that you installed it with `pip install fuzzinator` which installs it as a python2.7 application if that's your default. So my best guess is to try to install it explicitly with python3 target: `pip3 install fuzzinator`. Let me know whether it worked for you.

**Comment by renatahodovan** [comment]
@thapelomokwane Does the problem still exist or can we close the issue as solved?

**Comment by renatahodovan** [comment]
Closing because of inactivity.
